config/routes.rb
Depot::Application.routes.draw do
  get "admin" => "admin#index"
  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :users

  resources :pay_types

  
  
  get "store" => "store#index"
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :carts
    resources :orders
    resources :line_items do
      member do
        put 'decrement'
      end
    end
    root 'store#index'
  end

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    product = Product.find(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
      current_item.price = product.price
    end
    return current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price  }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    return quantity * price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include CurrentPayTypes
  
  def set_pay_types
    @pay_types = get_current_types
    return @pay_types
  end
  
  #PAYMENT_TYPES = self.set_pay_types
  
  has_many :line_items, dependent: :destroy
  validates :name, :email, :address, presence: true
  validates_presence_of :pay_type
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  
 
  
end

app/models/pay_type.rb
class PayType < ActiveRecord::Base

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :title, length: {minimum: 5, message: 'Длина названия должна быть больше 5 символов!'}
  has_attached_file :image_url, :styles => { :small => "150x150>" },
                    :url  => "/assets/images/:basename.:extension",
                    :path => ":rails_root/public/assets/images/:basename.:extension"

  validates_attachment_presence :image_url
  validates_attachment_size :image_url, :less_than => 5.megabytes
  validates_attachment_content_type :image_url, :content_type => ['image/jpeg', 'image/png']
  
  has_many :line_items
  has_many :orders, through: :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Товар находится в корзине')
      return false
    end
  end
  
  def self.latest
    return Product.order(:updated_at).last
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  after_destroy :ensure_an_admin_remains
  has_secure_password

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise 'Последний пользователь не может быть удалён'
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    if session[:user_id] != -1
      @user = User.find(session[:user_id])
    end
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:show, :create, :update, :destroy, :index]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #session[:counter] += 1
    if @cart.id != session[:cart_id]
      if session[:cart_id] == nil
        redirect_to store_url, notice: 'Неинициализированная корзина. Извините.'
      else
        redirect_to action: :show, id: session[:cart_id]
      end
    end
    if @cart.line_items.empty?
      @cart.destroy
      session[:cart_id] = nil
      redirect_to store_url, notice: 'Ваша корзина пуста'
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    if @cart.id == session[:cart_id] 
      @cart.destroy
      session[:cart_id] = nil  
    end    
    respond_to do |format|
      format.html { redirect_to store_url }
      format.js 
      format.json { head :no_content }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params[:cart]
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end
    
  protected
  def invalid_cart
    logger.error "Попытка доступа к неинициализированной корзине #{params[:id]}"
    redirect_to store_url, notice: 'Неинициализированная корзина. Извините.'
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  def index
    if params[:set_locale]
      redirect_to store_url(locale: params[:set_locale])
    else
      @products = Product.order(:title)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "Пользователь #{@user.name} был успешно создан" }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "Пользователь #{@user.name} был успешно обновлён" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice] = "Пользователь #{@user.name} успешно удалён"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pay_types_helper.rb
module PayTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h3 class="text-info">Добро пожаловать, <% if session[:user_id] != -1%><%= @user.name %><% else %>новый пользователь<% end %>.</h3>

<p class="text-justify">У нас имеется <%= pluralize(@total_orders, "заказ") %>.</p>
<% if @user.nil? %><p class="text-warning">Поспешите создать полноценного пользователя!</p><%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
    
      <div class="banner">
        <div class="container">
            <h1 class="text-right"><%= image_tag ('logo.png') %> <%= @page_title || t('.title') %></h1>
            <p class="text-right"><%= @page_subtitle || t('.subtitle') %></p>
        </div>
      </div>
      
    <div class="container-fluid">
        <div class ="row">
              <div class="col-md-2">
                <h3 style="margin-left: 25%;"><%= t('.locale') %></h3>
                <%= form_tag store_path, class: 'form-inline locale', method: 'GET', style: "margin-left: 25%;" do %>
                    <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()', class: 'form-control' %>
                    <%= submit_tag 'submit' %>
                    <%= javascript_tag "$('.locale input').hide()"%>
                <% end %>
              </div>
            <div class="col-md-7">
                <%= yield %>
            </div>
            
            <div class="col-md-3">
                <h2><%= t('.categories') %></h2>
                <nav class="navbar navbar-default" role="navigation">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                  <ul class="nav nav-pills nav-stacked">
                    <li <% if(controller.controller_name == 'store')  %> class="active"<% end %> role="presentation"><%= link_to t('.catalogue'), store_path %> </li>
                    <li id="cart-link"<% if(controller.controller_name == 'carts')  %> class="active"<% end %> role="presentation"><% if session[:cart_id] %><%= link_to t('.cart'), cart_path(session[:cart_id]) %><% end %></li>
                    <% if session[:user_id]%>
                        <li <% if(controller.controller_name == 'products')  %> class="active"<% end %> role="presentation"><%= link_to t('.products'), products_path %></li>
                        <li <% if(controller.controller_name == 'orders')  %> class="active"<% end %> role="presentation"><%= link_to t('.orders'), orders_path %></li>
                        <li <% if(controller.controller_name == 'users')  %> class="active"<% end %> role="presentation"><%= link_to t('.users'), users_path %></li>
                        <li <% if(controller.controller_name == 'sessions')  %> class="active"<% end %> role="presentation"><%= link_to t('.logout'), logout_path, method: :delete %></li>
                    <% else %>
                        <li <% if(controller.controller_name == 'sessions')  %> class="active"<% end %> role="presentation"><%= link_to t('.login'), login_path %></li>
                    <% end %>
                  </ul>
                </div><!-- /.navbar-collapse -->
              </nav>
                <h4 class='text-right'><%= t('.time_now') %><br/><small><%= @time %></small></h4>
                <div id="cart">
                    <% if @cart != nil %>
                      <%= render(@cart) %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

app/views/order_notifier/received.text.erb
Уважаемый <%= @order.name %>

Благодарим вас за заказ в лучшем в мире магазине Никиток для Никиток! Вы заказали следующие товары:

<%= render @order.line_items %>

Пока это всё!

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/app/views/order_notifier/shipped.text.erb